package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

const (
	generateDirective = "generate:reset"
	outputFile        = "reset.gen.go"
)

type structTarget struct {
	name string
}

type resetContext struct {
	pkg         *types.Package
	resetTypes  map[string]map[string]bool
}

func main() {
	root, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	if err := generate(root); err != nil {
		log.Fatal(err)
	}
}

func generate(root string) error {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
			packages.NeedTypes | packages.NeedTypesInfo | packages.NeedModule,
		Dir: root,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return fmt.Errorf("load packages: %w", err)
	}

	resetTypes := make(map[string]map[string]bool)
	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			continue
		}
		for _, target := range findResetStructs(pkg) {
			if resetTypes[pkg.PkgPath] == nil {
				resetTypes[pkg.PkgPath] = make(map[string]bool)
			}
			resetTypes[pkg.PkgPath][target.name] = true
		}
	}

	var loadErr error
	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			for _, e := range pkg.Errors {
				loadErr = fmt.Errorf("%s: %s", pkg.PkgPath, e.Msg)
			}
			continue
		}
		if pkg.Name == "main" && strings.HasSuffix(pkg.PkgPath, "/cmd/reset") {
			continue
		}
		if err := generatePackage(pkg, resetTypes); err != nil {
			return err
		}
	}

	return loadErr
}

func generatePackage(pkg *packages.Package, resetTypes map[string]map[string]bool) error {
	targets := findResetStructs(pkg)
	dir := packageDir(pkg)
	outPath := filepath.Join(dir, outputFile)

	if len(targets) == 0 {
		if err := os.Remove(outPath); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove %s: %w", outPath, err)
		}
		return nil
	}

	ctx := resetContext{
		pkg:        pkg.Types,
		resetTypes: resetTypes,
	}

	content, err := renderPackageFile(pkg.Name, targets, ctx)
	if err != nil {
		return fmt.Errorf("render %s: %w", pkg.PkgPath, err)
	}

	formatted, err := format.Source(content)
	if err != nil {
		return fmt.Errorf("format %s: %w", pkg.PkgPath, err)
	}

	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	return nil
}

func packageDir(pkg *packages.Package) string {
	if len(pkg.GoFiles) > 0 {
		return filepath.Dir(pkg.GoFiles[0])
	}
	if len(pkg.CompiledGoFiles) > 0 {
		return filepath.Dir(pkg.CompiledGoFiles[0])
	}
	return filepath.Dir(pkg.PkgPath)
}

func findResetStructs(pkg *packages.Package) []structTarget {
	var targets []structTarget

	for _, file := range pkg.Syntax {
		if file == nil || isGeneratedFile(pkg.Fset, file) {
			continue
		}

		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if _, ok := typeSpec.Type.(*ast.StructType); !ok {
					continue
				}
				if !hasGenerateReset(genDecl.Doc) && !hasGenerateReset(typeSpec.Doc) {
					continue
				}

				targets = append(targets, structTarget{name: typeSpec.Name.Name})
			}
		}
	}

	return targets
}

func isGeneratedFile(fset *token.FileSet, file *ast.File) bool {
	return strings.HasSuffix(filepath.Base(fset.Position(file.Name.Pos()).Filename), outputFile)
}

func hasGenerateReset(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, comment := range doc.List {
		text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
		if text == generateDirective {
			return true
		}
	}
	return false
}

func renderPackageFile(pkgName string, targets []structTarget, ctx resetContext) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	for _, target := range targets {
		obj := ctx.pkg.Scope().Lookup(target.name)
		if obj == nil {
			return nil, fmt.Errorf("type %s not found", target.name)
		}

		typeName, ok := obj.Type().(*types.Named)
		if !ok {
			return nil, fmt.Errorf("type %s is not a named type", target.name)
		}

		structType, ok := typeName.Underlying().(*types.Struct)
		if !ok {
			return nil, fmt.Errorf("type %s is not a struct", target.name)
		}

		receiver := strings.ToLower(target.name[:1])
		fmt.Fprintf(&buf, "func (%s *%s) Reset() {\n", receiver, target.name)
		fmt.Fprintf(&buf, "\tif %s == nil {\n", receiver)
		fmt.Fprintf(&buf, "\t\treturn\n")
		fmt.Fprintf(&buf, "\t}\n\n")

		for i := 0; i < structType.NumFields(); i++ {
			field := structType.Field(i)
			expr := receiver + "." + field.Name()
			for _, line := range resetStmts(expr, field.Type(), ctx) {
				fmt.Fprintf(&buf, "\t%s\n", line)
			}
		}

		fmt.Fprintf(&buf, "}\n\n")
	}

	return buf.Bytes(), nil
}

func resetStmts(expr string, typ types.Type, ctx resetContext) []string {
	typ = types.Unalias(typ)

	switch t := typ.(type) {
	case *types.Basic:
		return []string{fmt.Sprintf("%s = %s", expr, zeroLiteral(t))}
	case *types.Slice:
		return []string{fmt.Sprintf("%s = %s[:0]", expr, expr)}
	case *types.Map:
		return []string{fmt.Sprintf("clear(%s)", expr)}
	case *types.Pointer:
		if hasResetMethod(t.Elem(), ctx) {
			return resetMethodCall(expr, typ, ctx)
		}
		inner := resetStmts(derefExpr(expr), t.Elem(), ctx)
		lines := []string{fmt.Sprintf("if %s != nil {", expr)}
		for _, line := range inner {
			lines = append(lines, "\t"+line)
		}
		lines = append(lines, "}")
		return lines
	case *types.Array:
		return []string{fmt.Sprintf("%s = %s", expr, arrayZeroLiteral(t))}
	case *types.Chan, *types.Interface, *types.Signature:
		return []string{fmt.Sprintf("%s = nil", expr)}
	case *types.Struct:
		return resetStructFields(expr, t, ctx)
	case *types.Named:
		if hasResetMethod(t, ctx) {
			return resetMethodCall(expr, typ, ctx)
		}
		return resetStmts(expr, t.Underlying(), ctx)
	default:
		return nil
	}
}

func resetStructFields(expr string, str *types.Struct, ctx resetContext) []string {
	var lines []string
	for i := 0; i < str.NumFields(); i++ {
		field := str.Field(i)
		fieldExpr := expr + "." + field.Name()
		lines = append(lines, resetStmts(fieldExpr, field.Type(), ctx)...)
	}
	return lines
}

func hasResetMethod(typ types.Type, ctx resetContext) bool {
	typ = types.Unalias(typ)

	if pkgPath, name := namedTypePkgPath(typ); pkgPath != "" && ctx.resetTypes[pkgPath][name] {
		return true
	}

	if types.NewMethodSet(types.NewPointer(typ)).Lookup(ctx.pkg, "Reset") != nil {
		return true
	}
	return types.NewMethodSet(typ).Lookup(ctx.pkg, "Reset") != nil
}

func resetMethodCall(expr string, typ types.Type, ctx resetContext) []string {
	typ = types.Unalias(typ)

	if _, ok := typ.(*types.Pointer); ok {
		return []string{
			fmt.Sprintf("if resetter, ok := interface{}(%s).(interface{ Reset() }); ok && %s != nil {", expr, expr),
			"\tresetter.Reset()",
			"}",
		}
	}

	if types.NewMethodSet(types.NewPointer(typ)).Lookup(ctx.pkg, "Reset") != nil {
		return []string{fmt.Sprintf("(&%s).Reset()", expr)}
	}

	return []string{fmt.Sprintf("%s.Reset()", expr)}
}

func namedTypePkgPath(typ types.Type) (string, string) {
	named, ok := types.Unalias(typ).(*types.Named)
	if !ok {
		return "", ""
	}
	obj := named.Obj()
	if obj.Pkg() == nil {
		return "", ""
	}
	return obj.Pkg().Path(), obj.Name()
}

func derefExpr(expr string) string {
	return "*" + expr
}

func zeroLiteral(typ *types.Basic) string {
	switch typ.Kind() {
	case types.Bool:
		return "false"
	case types.String:
		return `""`
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64, types.Uintptr,
		types.Float32, types.Float64, types.Complex64, types.Complex128:
		return "0"
	case types.UnsafePointer:
		return "nil"
	default:
		return "0"
	}
}

func arrayZeroLiteral(arr *types.Array) string {
	elem := arr.Elem()
	switch e := types.Unalias(elem).(type) {
	case *types.Basic:
		return fmt.Sprintf("[%d]%s{}", arr.Len(), e.Name())
	case *types.Named:
		return fmt.Sprintf("[%d]%s{}", arr.Len(), e.Obj().Name())
	default:
		return fmt.Sprintf("[%d]%s{}", arr.Len(), types.TypeString(elem, nil))
	}
}
